### ISSUE TITLE
html validator home page still shows after 24 hours

### ISSUE THREAD

**Issue by imjustwondering** [mgueury/html_validator#30]
I've had html validator for firefox 57.0 for over 24 hours hours and have used it 8-9-10 times. On occasion when I start a new session of firefox the html validator home page comes up on a second tab
Of course it's distracting,  here's the page the tab is assigned to.
Just saying and thanks

http://users.skynet.be/mgueury/mozilla/new_webextension.html?version=0.9.8.3&browser=Firefox&platform=win

**Comment by mgueury** [comment]
It is abnormal. It should be appearing only when the current version is different from the last one. Ie, after 'upgrade' or 'installation'. I can not reproduce it here ? But it is true that I do not stop often my browser.

Question:
- From what I see you have Firefox on Windows and the last version.
- Which windows version ?
- When does it happen ? On startup of Firefox ? Other ?
- Do you shutdown your PC everyday ?
- Do you use special type of profile ?

Thanks

**Comment by imjustwondering** [comment]
Thank you for the reply   
   - Which windows version ?
   
   - 10   

   
   - When does it happen ? On startup of Firefox ? Other ?
   
   - On start up of Firefox, but only about 30-50% of the time. I don't have it installed on Chrome.   

   
   - Do you shutdown your PC everyday ?
   
   - Yes, at the end of the day   

   
   - Do you use special type of profile ?
   
   - No
Thanks again


 

    On Thursday, November 16, 2017, 3:15:03 PM EST, mgueury <notifications@github.com> wrote:  
 
 
It is abnormal. It should be appearing only when the current version is different from the last one. Ie, after 'upgrade' or 'installation'. I can not reproduce it here ? But it is true that I do not stop often my browser.

Question:
   
   - From what I see you have Firefox on Windows and the last version.
   - Which windows version ?
   - When does it happen ? On startup of Firefox ? Other ?
   - Do you shutdown your PC everyday ?
   - Do you use special type of profile ?

**Comment by mgueury** [comment]
Not sure if it is related. But I saw this error in the console in FF57 on Mac.

chrome.runtime.getPlatformInfo is not a function  tidy_platform_fake.js:36
	isNewInstall moz-extension://24e4e9d0-e0ae-784b-b65b-e30d76ca384e/common/tidy_platform_fake.js:36:5
	tidy_pref.load/< moz-extension://24e4e9d0-e0ae-784b-b65b-e30d76ca384e/common/tidy_platform_fake.js:10:7
	apply self-hosted:4107:5
	applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:283:16
	applySafeWithoutClone self-hosted:954:17
	wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:456:13

### To do
- check if it is the same problem for FF58.
- check if the function exist before to call it.
-> Probably a FF problem only.

**Comment by mgueury** [comment]
Solved the last message. But it is probably not the cause. It is only happening when opening Devtools and has, I think no consequence.

**Comment by mgueury** [comment]
Can you try this:
* In the URL of the browser, type "about:debugging".
* Enable debugging on the top of the page
* Then look for the HTML Validator extension and click Debug 
* Go in the console tab
* At the bottom, type this;

chrome.storage.sync.get(null, function (data) { console.info(data) });

And give back the result.
Normally tidy_pref_version should be 0.9.8.3

**Comment by mgueury** [comment]
Q2. After that the problem happened, look in the same console and seach for a line like this.

current_version: 0.9.8.3/ last_version: 0.9.8.3                                          tidy_platform_fake.js:23:5

Thanks

**Comment by mgueury** [comment]
Note for me:  https://github.com/mgueury/html_validator/blob/0.9.8.0/common/tidy_util.js.
Version 0.984. Removed isNewInstall from the old XUL version. 
This is the most probably cause for now.

**Comment by imjustwondering** [comment]
Hi, I did not see the issue yesterday at all and I loaded firefox many times yesterday.
I will email you tomorrow this time to inform you if the issue has occurred again.
Thank you for your troubles



 

    On Saturday, November 18, 2017, 3:11:38 PM EST, mgueury <notifications@github.com> wrote:  
 
 
Not sure if it is related. But I saw this error in the console in FF57 on Mac.

chrome.runtime.getPlatformInfo is not a function tidy_platform_fake.js:36
isNewInstall moz-extension://24e4e9d0-e0ae-784b-b65b-e30d76ca384e/common/tidy_platform_fake.js:36:5
tidy_pref.load/< moz-extension://24e4e9d0-e0ae-784b-b65b-e30d76ca384e/common/tidy_platform_fake.js:10:7
apply self-hosted:4107:5
applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:283:16
applySafeWithoutClone self-hosted:954:17
wrapPromise/< resource://gre/modules/ExtensionCommon.jsm:456:13

To do
   
   - check if it is the same problem for FF58.
   - check if the function exist before to call it.

**Comment by mgueury** [comment]
Please check if the issue is solved in 0.984. I just published it.

**Comment by mgueury** [comment]
The issue is I think fixed based after removing isNewInstall from the old XUL version.

The log was showing this: 
current_version: 0.9.8.3/ last_version: xxxx_todo_xxxx tidy_platform_fake.js:23:5
Instead of this:
current_version: 0.9.8.3/ last_version: 0.9.8.3 tidy_platform_fake.js:23:5

**Comment by imjustwondering** [comment]
It has not occured again

 

    On Friday, November 24, 2017, 11:57:39 AM EST, mgueury <notifications@github.com> wrote:  
 
 
Please check if the issue is solved in 0.984. I just published it.

**Comment by mgueury** [comment]
Please reopen if it is not fixed.
