### ISSUE TITLE
Dup issue #11 ? No errors but many warnings + no URL parsing for &

### ISSUE THREAD

**Issue by jombra** [mgueury/html_validator#35]
I spotted two errors which seems to be not covered by other bug reports.
The new validator seems to have worse output concerning 2 things:
1) A document using deprecated techniques for browser testing shows
    124 warnings and no errors with FF57/validator 0.9.8.3 -  but before
    48 errors and 2 warnings with FF56/validator 0.9.7 which was correct.
    An error should not be marked as warning - this output is no longer useful.
2) An URL address with "&" was marked as bad before (as it should) with advice
    to replace it by &amp; before - it is not even given as a warning (but a green hook)
    now and is only spotted when using "http://validator.w3.org/check?uri=..." for a check.
    So currently the validator is of very limited use while before it could show
    all the bugs and the online validation was no longer necessary.
I hope the behaviour of the former version can be reached again so it is really
useful for local test version and one has not to check the global web server version
with the online tool.
The current output is a big regression compared to the 0.9.7 version - which is a pity.
Best regards
JMB

**Comment by mgueury** [comment]
Please check #31 and #11.
I think that you fall on the issue of missing API in Firefox.

Please read also: http://users.skynet.be/mgueury/mozilla/roadmap.html
For a comparison of the features. 

Like you will see, the same extension works better today in Chrome :-/ 
https://chrome.google.com/webstore/detail/html-validator/mpbelhhnfhfjnaehkcnnaknldmnocglk

**Comment by mgueury** [comment]
If you could check your page with the issue above and the Chrome extension, this would help.

Another thing that I forgot is that OpenSP is not included yet in the 0.98 version. There is no support anymore for binary libraries. So, currently Tidy is compiled with Emscripten in javascript. I have to do the same for OpenSP. It will be there in a next version

**Comment by mgueury** [comment]
Project moved to Gitlab.
See https://gitlab.com/mgueury/html_validator/issues/35
