### ISSUE TITLE
Warnings for empty tags?

### ISSUE THREAD

**Issue by miketubby** [mgueury/html_validator#44]
Validator warns for empty tags that are legitimate. A couple of examples:

1. Google maps

Placeholder for where Google Maps JS API may drop a map:

        <div id='map'></div>

to validator this tag looks empty, but it isn't (or won't be).

2. Fontawesome SVG icons

Fontawesome icons are typically invoked by classes in an <i> tag, for example:

        <i class='fab fa-facebook fa-lg fa-fw'></i>

to validator this tag looks empty, but it isn't (or won't be) when the Fontawesome runtime JS has rendered the icon in place.

Hence my pages get lots of inappropriate warnings because the DOM tree says one thing but something different is displayed ...

Mike

**Comment by mgueury** [comment]
Hi Mike,

This warning makes sometimes sense and sometimes not.
Can you try this, (in fact to hide it):

- open your page
- open the developer tools / html validator tab
- look the list of your warnings. Then put your mouse on top of the warning that you would like to remove.
- Click on the small hidden eye to hide that warning.
- Then ok to confirm to hide it

It is not perfect but it is a start.

Thanks,

Marc

**Comment by mgueury** [comment]
Note, ideally, you need version 0,986 that persist better the preference of Webextension. It is currently available on Chrome, in a few day, maybe tomorrow on FF.

**Comment by mgueury** [comment]
Note: Version 0,987 was released yesterday on Firefox.

**Comment by mgueury** [comment]
There are several work-around:
- with the tidy algorithm, hide the warning like shown above
- or go in the options and change the algorithm to "online" where W3c online validator will be used and this will not be shown
- in future version, the opensp algorithm that was there in previous FF version will not show this behavior

Closing. Do not hesitate to reopen.
