### ISSUE TITLE
"Bigger toolbar" not working correctly in vertical mode

### ISSUE THREAD

**Issue by ssteinkellner** [mgueury/html_validator#60]
Hi,

in the new version 0.99 the bigger toolbar seems to only work correctly, when you open the chrome developer tools in horizontal mode. When opened in vertical mode, it looks like this:
![image](https://user-images.githubusercontent.com/6803767/126946809-7030b024-748f-4b3b-929b-e549640c9980.png)

**Comment by mgueury** [comment]
Thanks for the report. Working on it.

**Comment by mgueury** [comment]
Fixed in 0.99.5. It should be released in a few days.
