### ISSUE TITLE
Un-Hiding warnings not possible?!

### ISSUE THREAD

**Issue by LaborMatthias** [mgueury/html_validator#61]
I clicked to hide some warnings. Now I am not able to
* See WHAT I did hide
* un-hide anything
I saw the theoretical ability using burger-menu -> Options -> Filter -> Hidden Errors and Warnings
but that textarea-like box is completely empty, "remove" does not do anything

**Comment by LaborMatthias** [comment]
Re-installing the plugin solved at least the issue that I could not unhide the warnings

**Comment by mgueury** [comment]
Thanks for reporting the issue. The bug was introduced in the previous major version after a lot of changes. Working on it.

**Comment by mgueury** [comment]
Fixed in 0.9.9.6
